config/routes.rb
Rails.application.routes.draw do
  root 'flights#index'
  resources :bookings

  resources :flights
  

end

app/models/airport.rb
class Airport < ActiveRecord::Base
  has_many :departing_flights, class_name: "Flight", foreign_key: :start_id
  has_many :arriving_flights,  class_name: "Flight", foreign_key: :finish_id


end

app/models/booking.rb
class Booking < ActiveRecord::Base
  has_many :passengers
  belongs_to :flight


  accepts_nested_attributes_for :passengers
end

app/models/flight.rb
class Flight < ActiveRecord::Base
  belongs_to :from_airport,  class_name: "Airport", foreign_key: :start_id
  belongs_to :to_airport,   class_name: "Airport", foreign_key: :finish_id
  has_many :bookings

  def self.date_list
    dates = Flight.all.order(start_time: :asc)
    dates.map {|n| n.start_time.strftime("%d/%m/%Y") }.uniq
  end

  def self.search(depart, dest, date)
    Flight.where(start_id: depart,
     finish_id: dest,
     start_time: Flight.correct_date(date))

  end

  def self.correct_date(date)
   		unless date.nil?
   			date = date.to_date
   			date.beginning_of_day..date.end_of_day
   		end
  end

end

app/models/passenger.rb
class Passenger < ActiveRecord::Base
  belongs_to :booking
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @flight = Flight.find(params[:flight_id])
    @booking = Booking.new
    @passengers = params[:passengers].to_i
    @passengers.times { @booking.passengers.build }

  end

  def show
    @booking = Booking.find(params[:id])
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.save
    redirect_to booking_path(@booking)
  end

  private

  def booking_params
    params.require(:booking).permit(:flight_id, passengers_attributes: [:id, :name, :email])
  end


end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController

  def index
    @airports = Airport.all.map { |a| [ a.airport_code, a.id ] }
  
    @passenger_number = [1, 2, 3, 4]

    @start_time = params[:start_time]
    @from_airport = params[:start_id]
    @to_airport = params[:finish_id]

    @passengers = params[:passengers]
    @flights = Flight.search(params[:start_id],
                             params[:finish_id],
                             params[:start_time])

 end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/bookings/new.html.erb
<h1>Confirm your booking</h1>

<h3>Your flight</h3>

    <p>Flight No.:<%= @flight.id %></p>
    <p> From: <%= @flight.from_airport.airport_code %> </p>
    <p> To: <%= @flight.to_airport.airport_code %> </p>
    <p> Date: <%= @flight.start_time.strftime("%A, %B %e, %Y") %>



<%= form_for (@booking) do |f| %>

<%= hidden_field_tag(:passengers, params[:passengers]) %>
<%= f.hidden_field(:flight_id, value: params[:flight_id]) %>
<%= hidden_field_tag(:flight_id, params[:flight_id]) %>

  <%= f.fields_for :passengers do |p| %>
    Passengers: <%= @passengers %><br />
  <%= p.label :name %>

  <%= p.text_field :name %>
  <%= p.label :email %>
  <%= p.email_field :email %>
  <% end %>

<%= f.submit "Save booking" %>

<% end %>

app/views/bookings/show.html.erb
<h1>Confirmation</h1>

<h3>Your flight</h3>

    <p>Flight No.:<%= @booking.id %></p>
    <p> From: <%= @booking.flight.from_airport.airport_code %> </p>
    <p> To: <%= @booking.flight.to_airport.airport_code %> </p>
    <p> Date: <%= @booking.flight.start_time.strftime("%A, %B %e, %Y") %>




    <% @booking.passengers.each do |passenger| %>
      <li> <%="#{passenger.name} <#{passenger.email}>" %></li>
  <% end %>

app/views/flights/index.html.erb
<h1>Book your flight</h1>

<%= form_tag(flights_path, method: :get) do %>

  <%= label_tag(:start_id, "from") %>
  <%= select_tag(:start_id,  options_for_select(@airports)) %>
  <%= label_tag(:finish_id, "to") %>
  <%= select_tag(:finish_id,  options_for_select(@airports)) %>
  <%= label_tag(:passengers, "passengers") %>
  <%= select_tag(:passengers, options_for_select([1, 2, 3, 4])) %>
  <%= label_tag(:start_time, "Select date") %>
  <%= select_tag(:start_time, options_for_select(Flight.date_list)) %>
  <%= submit_tag "Search" %>

<% end %>
<%= form_tag(new_booking_path, method: :get ) do %>
  <%= hidden_field_tag :passengers, params[:passengers] %>

  <h3>Flights found</h3>
   <table class="table table-striped">
 <thead>
   <tr>
     <th>Flight No. </th>
     <th>From </th>
     <th>To </th>
     <th>Date </th>
   </tr>
   </thead>
   <tbody>

      <% @flights.each do |flight| %>
      <tr>
      <td><%= radio_button_tag(:flight_id, flight.id) %>
      No.:<%= flight.id %></td>
      <td> <%= flight.from_airport.airport_code %> </td>
      <td>  <%= flight.to_airport.airport_code %> </td>
      <td>  <%= flight.start_time.strftime("%A, %B %e, %Y") %></td>
      <td><%= submit_tag "Book flights" %></td>
        <% end %>
    </tr>
  </tbody>
</table>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> Odin Flight Booker </title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>
  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "Flight Booker", root_url, class: "navbar-brand logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home",   '#' %></li>
            <li><%= link_to "Help",   '#' %></li>
            <li><%= link_to "Log in", '#' %></li>
          </ul>
        </nav>
      </div>
    </header>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>